# Generated by Django 5.0.1 on 2024-02-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(4, 'En Ejecucion'), (3, 'Confirmado'), (2, 'Por Confirmar'), (1, 'Reservado'), (5, 'Anulada')], default=1),
        ),
    ]
