# Generated by Django 5.0.1 on 2024-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
