# Generated by Django 4.2.10 on 2024-02-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('En_ejecucion', 'Ejecución'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='Reservado', max_length=20),
        ),
    ]
