# Generated by Django 4.2.10 on 2024-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('En ejecucion', 'Ejecución'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], default='Reservado', max_length=20),
        ),
    ]
