# Generated by Django 5.0.1 on 2024-02-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='code',
        ),
    ]
