# Generated by Django 5.0.1 on 2024-02-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('bookings', '0005_remove_booking_code'),
    ]

    operations = [
    ]
