# Generated by Django 5.0.1 on 2024-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Reservado'), (2, 'Por Confirmar'), (3, 'Confirmado'), (4, 'En Ejecucion'), (5, 'Anulada')], default=1),
        ),
    ]