# Generated by Django 5.0.1 on 2024-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(max_length=50),
        ),
    ]
